### ISSUE TITLE
Tracking issues

### ISSUE THREAD

**Issue by irevoire** [irevoire/database#1]
- [ ] Make the code less ugly by using `mmap` on clean segments
- [ ] Find a way to get benchmarks
- [ ] Fix at which time we dump the memtable in a clean segment (currently, I’m reading the number of entries in the memtable, but I should look at the number of bytes allocated in memory)
- [ ] Have some kind of metadata to know how many segments I should merge and when, maybe?
- [ ] Introduce metadata in the segments to find entries faster (probably fixed size indexes to all the keys?)
- [ ] Introduce range queries/iterator
- [ ] Introduce deletions
- [ ] Introduce a bloom filter to know faster if something _is_ in the database
